// Place any global data in this file.
// You can import this data from anywhere in your site by using the `import` keyword.

export const SITE_TITLE = 'Astro Blog';
export const SITE_DESCRIPTION = 'Welcome to my website!';

// Giscus (https://giscus.app) powers the comment box at the end of every blog
// post, storing comments as GitHub Discussions on GISCUS_REPO. The three IDs
// below are generated by the giscus.app setup wizard for that repo and are
// filled in by hand later; until all of them are set, Giscus.astro renders no
// comment box at all (see isGiscusConfigured in src/lib/giscus.ts).
export const GISCUS_REPO = 'automateeverythingM/blog';
export const GISCUS_REPO_ID = '';
export const GISCUS_CATEGORY = '';
export const GISCUS_CATEGORY_ID = '';
